#!/bin/sh
#
# Copyright (c) 2012 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
#
# TODO(yhong): This file is a duplicated from factory/setup/create_hwid_bundle.
#     Remove this file after CPFE stop using it.
#
# This is a self-extraction package for ChromeOS HWID.
# Syntax: $0 [stateful_partition_device]

START_DIR="$(pwd)"
MOUNT_DIR=""
TARGET_BASE_MOUNT="dev_image/factory"
TARGET_BASE_LIVE="/usr/local/factory"
TARGET_NAME="hwid"

on_exit() {
  cd "$START_DIR"
  if [ -d "$MOUNT_DIR" ]; then
    sudo umount "$MOUNT_DIR" || true
    rmdir "$MOUNT_DIR" || true
  fi
}

die() {
  echo "ERROR: $*" 1>&2
  exit 1
}

die_usage() {
  die "Usage: $0 [stateful_partition_device_or_folder]"
}

setup_target() {
  local target_dir=""
  local recreate_folder="TRUE"

  case "$#" in
    0 )
      target_dir="$TARGET_BASE_LIVE/$TARGET_NAME"
      echo "Updating live image path $target_dir..."
      ;;
    1 )
      local state_dev="$1"
      if [ -b "$state_dev" ]; then
        echo "Updating to stateful partition $state_dev..."
        MOUNT_DIR="$(mktemp -d /tmp/hwid_XXXXXXXX)"
        sudo mount "$state_dev" "$MOUNT_DIR" || die "Failed to mount."
        target_dir="$MOUNT_DIR/$TARGET_BASE_MOUNT/$TARGET_NAME"
      elif [ -d "$state_dev" ]; then
        echo "Updating to folder $state_dev..."
        target_dir="$state_dev"
        # This is usually for manually debugging so don't remove existing files
        recreate_folder=""
      else
        die_usage
      fi
      ;;
    * )
      die_usage
      ;;
  esac

  if [ -n "$recreate_folder" ]; then
    # For a valid target, the parent folder should alread exist.
    if [ ! -d "$(dirname "$target_dir")" ]; then
      die "Invalid target ($target_dir). Missing required folders."
    fi
    # Now, update $target_dir
    sudo rm -rf "$target_dir" || die "Failed to erase $target_dir"
    sudo mkdir -p "$target_dir" || die "Failed to mkdir $target_dir"
  fi

  # Move to $target_dir for file extraction
  cd "$target_dir"
}

set -e
trap on_exit EXIT
setup_target "$@"

# force shar to overwrite files
set -- "-c"

# ----- Following data is generated by shar -----
#!/bin/sh
lock_dir=_sh43073
MD5SUM=${MD5SUM-md5sum}
f=`${MD5SUM} --version | egrep '^md5sum .*(core|text)utils'`
test -n "${f}" && md5check=true || md5check=false
${md5check} || \
  echo 'Note: not verifying md5sums.  Consider installing GNU coreutils.'
if test "X$1" = "X-c"
then keep_file=''
else keep_file=true
fi
echo=echo
save_IFS="${IFS}"
IFS="${IFS}:"
gettext_dir=
locale_dir=
set_echo=false

for dir in $PATH
do
  if test -f $dir/gettext \
     && ($dir/gettext --version >/dev/null 2>&1)
  then
    case `$dir/gettext --version 2>&1 | sed 1q` in
      *GNU*) gettext_dir=$dir
      set_echo=true
      break ;;
    esac
  fi
done

if ${set_echo}
then
  set_echo=false
  for dir in $PATH
  do
    if test -f $dir/shar \
       && ($dir/shar --print-text-domain-dir >/dev/null 2>&1)
    then
      locale_dir=`$dir/shar --print-text-domain-dir`
      set_echo=true
      break
    fi
  done

  if ${set_echo}
  then
    TEXTDOMAINDIR=$locale_dir
    export TEXTDOMAINDIR
    TEXTDOMAIN=sharutils
    export TEXTDOMAIN
    echo="$gettext_dir/gettext -s"
  fi
fi
IFS="$save_IFS"
if (echo "testing\c"; echo 1,2,3) | grep c >/dev/null
then if (echo -n test; echo 1,2,3) | grep n >/dev/null
     then shar_n= shar_c='
'
     else shar_n=-n shar_c= ; fi
else shar_n= shar_c='\c' ; fi
f=shar-touch.$$
st1=200112312359.59
st2=123123592001.59
st2tr=123123592001.5 # old SysV 14-char limit
st3=1231235901

if   touch -am -t ${st1} ${f} >/dev/null 2>&1 && \
     test ! -f ${st1} && test -f ${f}; then
  shar_touch='touch -am -t $1$2$3$4$5$6.$7 "$8"'

elif touch -am ${st2} ${f} >/dev/null 2>&1 && \
     test ! -f ${st2} && test ! -f ${st2tr} && test -f ${f}; then
  shar_touch='touch -am $3$4$5$6$1$2.$7 "$8"'

elif touch -am ${st3} ${f} >/dev/null 2>&1 && \
     test ! -f ${st3} && test -f ${f}; then
  shar_touch='touch -am $3$4$5$6$2 "$8"'

else
  shar_touch=:
  echo
  ${echo} 'WARNING: not restoring timestamps.  Consider getting and
installing GNU '\''touch'\'', distributed in GNU coreutils...'
  echo
fi
rm -f ${st1} ${st2} ${st2tr} ${st3} ${f}
#
if test ! -d ${lock_dir} ; then :
else ${echo} "lock directory ${lock_dir} exists"
     exit 1
fi
if mkdir ${lock_dir}
then ${echo} "x - created lock directory ${lock_dir}."
else ${echo} "x - failed to create lock directory ${lock_dir}."
     exit 1
fi
if test -n "${keep_file}" && test -f 'DELBIN'
then
${echo} "x - SKIPPING DELBIN (file already exists)"

else
${echo} "x - extracting DELBIN (text)"
  sed 's/^X//' << 'SHAR_EOF' > 'DELBIN' &&
X
X
X
X##### BEGIN CHECKSUM BLOCK
X#
X# WARNING: This checksum is generated and audited by Google. Do not
X# modify it. If you modify it, devices' configurations will be
X# invalid, and the devices may not be sold.
X#
X# 警告：此校验码由 Google 产生及审核，禁止手动修改。
X# 若修改将使设备配置變為无效，并且不得销售此设备。
X#
X#####
Xchecksum: b68c411d2bc2c59613d121bc88fca2ccd70ae9d1
X
X##### END CHECKSUM BLOCK. See the warning above. 请参考上面的警告。
X
X
Xproject: DELBIN
X
Xencoding_patterns:
X  0: default
X
Ximage_id:
X  0: PROTO
X  1: EVT
X  2: DVT
X  3: PVT
X
Xpattern:
X- image_ids:
X  - 0
X  - 1
X  - 2
X  - 3
X  encoding_scheme: base8192
X  fields:
X  - mainboard_field: 3
X  - region_field: 5
X  - dram_field: 5
X  - cpu_field: 3
X  - storage_field: 5
X  - ro_main_firmware_field: 5
X  - firmware_keys_field: 3
X  - ro_ec_firmware_field: 5
X  - stylus_field: 0
X  - tpm_field: 0
X  - audio_codec_field: 2
X  - touchscreen_field: 0
X  - touchpad_field: 0
X  - video_field: 0
X  - wireless_field: 0
X  - chassis_field: 0
X  - ec_flash_chip_field: 0
X  - usb_hosts_field: 0
X  - bluetooth_field: 0
X  - battery_field: 0
X  - embedded_controller_field: 0
X  - display_panel_field: 2
X  - flash_chip_field: 0
X  - video_field: 1
X  - ec_flash_chip_field: 1
X  - embedded_controller_field: 1
X
Xencoded_fields:
X  region_field: !region_field
X  - us
X  - gb
X  - jp.us
X  - za.us
X  - nl
X  - sg
X  - au
X  - id
X  - nz
X  - ph
X  - my
X  - hk
X  - br.usintl
X  - za
X  - ie
X  - nordic
X  - pl
X  - ch
X  - il
X  - it
X  - jp
X  - pt
X  - tr
X  - be
X  - gr
X  stylus_field:
X    0:
X      stylus: ELAN9008_00_04F3_2C1C
X  tpm_field:
X    0:
X      tpm: '2_0_0_0'
X  audio_codec_field:
X    0:
X      audio_codec:
X      - i2c_10EC5682_00
X      - i2c_MX98373_00
X      - i2c_MX98373_01
X    1:
X      audio_codec:
X      - 0000_00_1f_3
X      - Intel_Tigerlake_HDMI
X      - dmic_codec
X      - ehdaudio0D2
X      - i2c_10EC5682_00
X      - i2c_MX98373_00
X      - i2c_MX98373_01
X    2:
X      audio_codec:
X      - 0000_00_1f_3
X      - dmic_codec
X      - ehdaudio0D2
X      - i2c_10EC5682_00
X      - i2c_MX98373_00
X      - i2c_MX98373_01
X  touchscreen_field:
X    0:
X      touchscreen: ELAN9008_00_04F3_2C1C
X  touchpad_field:
X    0:
X      touchpad: Elan_Touchpad
X  video_field:
X    0:
X      video: Quanta
X    1:
X      video: Quanta_30d6
X  wireless_field:
X    0:
X      wireless: wireless_cc8d134f
X  chassis_field:
X    0:
X      chassis: DELBIN
X  mainboard_field:
X    0:
X      mainboard: '1_0'
X    1:
X      mainboard: rev2
X    2:
X      mainboard: rev3
X  storage_field:
X    0:
X      storage: storage_a9c1468f
X    1:
X      storage: storage_hynix_256gb
X    2:
X      storage: storage_wd_256gb
X    3:
X      storage: storage_hynix_128gb
X  ro_main_firmware_field:
X    0:
X      ro_main_firmware: Google_Delbin_13360_0_2020_07_20_1857
X    1:
X      ro_main_firmware: Google_Delbin_13406_0_0
X    2:
X      ro_main_firmware: Google_Delbin_13432_0_2020_08_31_2251
X    3:
X      ro_main_firmware: Google_Delbin_13521_58_0
X    4:
X      ro_main_firmware: Google_Delbin_13521_62_0
X    5:
X      ro_main_firmware: Google_Delbin_13672_30_0
X    6:
X      ro_main_firmware: Google_Delbin_13672_39_0
X  ec_flash_chip_field:
X    0:
X      ec_flash_chip: NPCX796F
X    1:
X      ec_flash_chip: NPCX797F
X  ro_ec_firmware_field:
X    0:
X      ro_ec_firmware: delbin_v2_0_4451_b5e4045dc
X    1:
X      ro_ec_firmware: delbin_v2_0_5090_20b44a3f5
X    2:
X      ro_ec_firmware: delbin_v2_0_5214cf7b8c404
X    3:
X      ro_ec_firmware: delbin_v2_0_6343_aef401423
X    4:
X      ro_ec_firmware: delbin_v2_0_6343_aef401423_1
X    5:
X      ro_ec_firmware: delbin_v2_0_6785_1333a05a3
X    6:
X      ro_ec_firmware: delbin_v2_0_7093_edfd0fddb
X  usb_hosts_field:
X    0:
X      usb_hosts:
X      - usb_hosts_6f950346
X      - usb_hosts_6f950346
X      - usb_hosts_bc72c0a2
X      - usb_hosts_bc72c0a2
X  bluetooth_field:
X    0:
X      bluetooth: bluetooth_17161aca
X  cpu_field:
X    0:
X      cpu: 11th_Gen_IntelR_CoreTM_i7_1165G7_2_80GHz
X    1:
X      cpu: 11th_Gen_IntelR_CoreTM_i5_1135G7_2_40GHz
X    2:
X      cpu: 11th_Gen_IntelR_CoreTM_i3_1115G4_3_00GHz
X  battery_field:
X    0:
X      battery: AS3GXAE
X  embedded_controller_field:
X    0:
X      embedded_controller: NPCX796F
X    1:
X      embedded_controller: NPCX797F
X  firmware_keys_field:
X    0:
X      firmware_keys: firmware_keys_dev
X    1:
X      firmware_keys: firmware_keys_dev_evt
X    2:
X      firmware_keys: firmware_keys_mp
X  dram_field:
X    0:
X      dram:
X      - MT53E1G32D2NP-046_WT_A_2048mb_0
X      - MT53E1G32D2NP-046_WT_A_2048mb_1
X      - MT53E1G32D2NP-046_WT_A_2048mb_2
X      - MT53E1G32D2NP-046_WT_A_2048mb_3
X      - MT53E1G32D2NP-046_WT_A_2048mb_4
X      - MT53E1G32D2NP-046_WT_A_2048mb_5
X      - MT53E1G32D2NP-046_WT_A_2048mb_6
X      - MT53E1G32D2NP-046_WT_A_2048mb_7
X    1:
X      dram:
X      - H9HCNNNBKMMLXR-NEE_1024mb_0
X      - H9HCNNNBKMMLXR-NEE_1024mb_1
X      - H9HCNNNBKMMLXR-NEE_1024mb_2
X      - H9HCNNNBKMMLXR-NEE_1024mb_3
X      - H9HCNNNBKMMLXR-NEE_1024mb_4
X      - H9HCNNNBKMMLXR-NEE_1024mb_5
X      - H9HCNNNBKMMLXR-NEE_1024mb_6
X      - H9HCNNNBKMMLXR-NEE_1024mb_7
X    2:
X      dram:
X      - MT53E512M32D2NP-046WT_E_1024mb_0
X      - MT53E512M32D2NP-046WT_E_1024mb_1
X      - MT53E512M32D2NP-046WT_E_1024mb_2
X      - MT53E512M32D2NP-046WT_E_1024mb_3
X      - MT53E512M32D2NP-046WT_E_1024mb_4
X      - MT53E512M32D2NP-046WT_E_1024mb_5
X      - MT53E512M32D2NP-046WT_E_1024mb_6
X      - MT53E512M32D2NP-046WT_E_1024mb_7
X    3:
X      dram:
X      - MT53E512M32D2NP-046WT_E_1024mb_0_1
X      - MT53E512M32D2NP-046WT_E_1024mb_1_1
X      - MT53E512M32D2NP-046WT_E_1024mb_2_1
X      - MT53E512M32D2NP-046WT_E_1024mb_3_1
X    4:
X      dram:
X      - H9HCNNNCPMMLXR-NEE_2048mb_0
X      - H9HCNNNCPMMLXR-NEE_2048mb_1
X      - H9HCNNNCPMMLXR-NEE_2048mb_2
X      - H9HCNNNCPMMLXR-NEE_2048mb_3
X      - H9HCNNNCPMMLXR-NEE_2048mb_4
X      - H9HCNNNCPMMLXR-NEE_2048mb_5
X      - H9HCNNNCPMMLXR-NEE_2048mb_6
X      - H9HCNNNCPMMLXR-NEE_2048mb_7
X    5:
X      dram:
X      - MT53E512M32D2NP-046WT_E_1024mb_0_1
X      - MT53E512M32D2NP-046WT_E_1024mb_1_1
X      - MT53E512M32D2NP-046WT_E_1024mb_2_1
X      - MT53E512M32D2NP-046WT_E_1024mb_3_1
X      - MT53E512M32D2NP-046WT_E_1024mb_4_1
X      - MT53E512M32D2NP-046WT_E_1024mb_5_1
X      - MT53E512M32D2NP-046WT_E_1024mb_6_1
X      - MT53E512M32D2NP-046WT_E_1024mb_7_1
X    6:
X      dram:
X      - H9HCNNNCPMMLXR-NEE_4096mb_0
X      - H9HCNNNCPMMLXR-NEE_4096mb_1
X      - H9HCNNNCPMMLXR-NEE_4096mb_2
X      - H9HCNNNCPMMLXR-NEE_4096mb_3
X      - H9HCNNNCPMMLXR-NEE_4096mb_4
X      - H9HCNNNCPMMLXR-NEE_4096mb_5
X      - H9HCNNNCPMMLXR-NEE_4096mb_6
X      - H9HCNNNCPMMLXR-NEE_4096mb_7
X    7:
X      dram:
X      - H9HCNNNBKMMLXR-NEE_1024mb_0_1
X      - H9HCNNNBKMMLXR-NEE_1024mb_1_1
X      - H9HCNNNBKMMLXR-NEE_1024mb_2_1
X      - H9HCNNNBKMMLXR-NEE_1024mb_3_1
X      - H9HCNNNBKMMLXR-NEE_1024mb_4_1
X      - H9HCNNNBKMMLXR-NEE_1024mb_5_1
X      - H9HCNNNBKMMLXR-NEE_1024mb_6_1
X      - H9HCNNNBKMMLXR-NEE_1024mb_7_1
X  display_panel_field:
X    0:
X      display_panel: display_panel_3971777f
X    1:
X      display_panel: display_panel_676cc623
X  flash_chip_field:
X    0:
X      flash_chip: W25Q256JV_M
X
Xcomponents:
X  region: !region_component
X  audio_codec:
X    items:
X      i2c_10EC5682_00:
X        values:
X          name: i2c-10EC5682:00
X      i2c_MX98373_01:
X        values:
X          name: i2c-MX98373:01
X      i2c_MX98373_00:
X        values:
X          name: i2c-MX98373:00
X      0000_00_1f_3:
X        values:
X          name: 0000:00:1f.3
X      dmic_codec:
X        values:
X          name: dmic-codec
X      ehdaudio0D2:
X        values:
X          name: ehdaudio0D2
X      Intel_Tigerlake_HDMI:
X        values:
X          name: Intel Tigerlake HDMI
X  battery:
X    items:
X      AS3GXAE:
X        values:
X          manufacturer: AS3GXAE
X          model_name: C536-49
X          technology: Li-ion
X  bluetooth:
X    items:
X      bluetooth_17161aca:
X        values:
X          bcdDevice: '0002'
X          idProduct: '0026'
X          idVendor: '8087'
X  mainboard:
X    items:
X      '1_0':
X        status: unqualified
X        values:
X          version: '1.0'
X      rev2:
X        status: unqualified
X        values:
X          version: rev2
X      rev3:
X        values:
X          version: rev3
X  chassis:
X    items:
X      DELBIN:
X        values: null
X  cpu:
X    items:
X      11th_Gen_IntelR_CoreTM_i7_1165G7_2_80GHz:
X        values:
X          cores: '8'
X          model: 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
X      11th_Gen_IntelR_CoreTM_i5_1135G7_2_40GHz:
X        values:
X          cores: '8'
X          model: 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
X      11th_Gen_IntelR_CoreTM_i3_1115G4_3_00GHz:
X        values:
X          cores: '4'
X          model: 11th Gen Intel(R) Core(TM) i3-1115G4 @ 3.00GHz
X  display_panel:
X    items:
X      display_panel_3971777f:
X        values:
X          height: '1080'
X          product_id: '0046'
X          vendor: NCP
X          width: '1920'
X      display_panel_676cc623:
X        status: unqualified
X        values:
X          height: '1080'
X          product_id: 15e8
X          vendor: CMN
X          width: '1920'
X  dram:
X    items:
X      MT53E1G32D2NP-046_WT_A_2048mb_0:
X        status: unqualified
X        values:
X          part: MT53E1G32D2NP-046_WT_A
X          size: '2048'
X          slot: '0'
X          timing: LPDDR4-4267
X      MT53E1G32D2NP-046_WT_A_2048mb_1:
X        status: unqualified
X        values:
X          part: MT53E1G32D2NP-046_WT_A
X          size: '2048'
X          slot: '1'
X          timing: LPDDR4-4267
X      MT53E1G32D2NP-046_WT_A_2048mb_2:
X        status: unqualified
X        values:
X          part: MT53E1G32D2NP-046_WT_A
X          size: '2048'
X          slot: '2'
X          timing: LPDDR4-4267
X      MT53E1G32D2NP-046_WT_A_2048mb_3:
X        status: unqualified
X        values:
X          part: MT53E1G32D2NP-046_WT_A
X          size: '2048'
X          slot: '3'
X          timing: LPDDR4-4267
X      MT53E1G32D2NP-046_WT_A_2048mb_4:
X        status: unqualified
X        values:
X          part: MT53E1G32D2NP-046_WT_A
X          size: '2048'
X          slot: '4'
X          timing: LPDDR4-4267
X      MT53E1G32D2NP-046_WT_A_2048mb_5:
X        status: unqualified
X        values:
X          part: MT53E1G32D2NP-046_WT_A
X          size: '2048'
X          slot: '5'
X          timing: LPDDR4-4267
X      MT53E1G32D2NP-046_WT_A_2048mb_6:
X        status: unqualified
X        values:
X          part: MT53E1G32D2NP-046_WT_A
X          size: '2048'
X          slot: '6'
X          timing: LPDDR4-4267
X      MT53E1G32D2NP-046_WT_A_2048mb_7:
X        status: unqualified
X        values:
X          part: MT53E1G32D2NP-046_WT_A
X          size: '2048'
X          slot: '7'
X          timing: LPDDR4-4267
X      H9HCNNNBKMMLXR-NEE_1024mb_0:
X        values:
X          part: H9HCNNNBKMMLXR-NEE
X          size: '1024'
X          slot: '0'
X          timing: LPDDR4-4267
X      H9HCNNNBKMMLXR-NEE_1024mb_1:
X        values:
X          part: H9HCNNNBKMMLXR-NEE
X          size: '1024'
X          slot: '1'
X          timing: LPDDR4-4267
X      H9HCNNNBKMMLXR-NEE_1024mb_2:
X        values:
X          part: H9HCNNNBKMMLXR-NEE
X          size: '1024'
X          slot: '2'
X          timing: LPDDR4-4267
X      H9HCNNNBKMMLXR-NEE_1024mb_3:
X        values:
X          part: H9HCNNNBKMMLXR-NEE
X          size: '1024'
X          slot: '3'
X          timing: LPDDR4-4267
X      H9HCNNNBKMMLXR-NEE_1024mb_4:
X        values:
X          part: H9HCNNNBKMMLXR-NEE
X          size: '1024'
X          slot: '4'
X          timing: LPDDR4-4267
X      H9HCNNNBKMMLXR-NEE_1024mb_5:
X        values:
X          part: H9HCNNNBKMMLXR-NEE
X          size: '1024'
X          slot: '5'
X          timing: LPDDR4-4267
X      H9HCNNNBKMMLXR-NEE_1024mb_6:
X        values:
X          part: H9HCNNNBKMMLXR-NEE
X          size: '1024'
X          slot: '6'
X          timing: LPDDR4-4267
X      H9HCNNNBKMMLXR-NEE_1024mb_7:
X        values:
X          part: H9HCNNNBKMMLXR-NEE
X          size: '1024'
X          slot: '7'
X          timing: LPDDR4-4267
X      MT53E512M32D2NP-046WT_E_1024mb_0:
X        values:
X          part: MT53E512M32D2NP-046WT_E
X          size: '1024'
X          slot: '0'
X          timing: LPDDR4-4267
X      MT53E512M32D2NP-046WT_E_1024mb_1:
X        values:
X          part: MT53E512M32D2NP-046WT_E
X          size: '1024'
X          slot: '1'
X          timing: LPDDR4-4267
X      MT53E512M32D2NP-046WT_E_1024mb_2:
X        values:
X          part: MT53E512M32D2NP-046WT_E
X          size: '1024'
X          slot: '2'
X          timing: LPDDR4-4267
X      MT53E512M32D2NP-046WT_E_1024mb_3:
X        values:
X          part: MT53E512M32D2NP-046WT_E
X          size: '1024'
X          slot: '3'
X          timing: LPDDR4-4267
X      MT53E512M32D2NP-046WT_E_1024mb_4:
X        values:
X          part: MT53E512M32D2NP-046WT_E
X          size: '1024'
X          slot: '4'
X          timing: LPDDR4-4267
X      MT53E512M32D2NP-046WT_E_1024mb_5:
X        values:
X          part: MT53E512M32D2NP-046WT_E
X          size: '1024'
X          slot: '5'
X          timing: LPDDR4-4267
X      MT53E512M32D2NP-046WT_E_1024mb_6:
X        values:
X          part: MT53E512M32D2NP-046WT_E
X          size: '1024'
X          slot: '6'
X          timing: LPDDR4-4267
X      MT53E512M32D2NP-046WT_E_1024mb_7:
X        values:
X          part: MT53E512M32D2NP-046WT_E
X          size: '1024'
X          slot: '7'
X          timing: LPDDR4-4267
X      MT53E512M32D2NP-046WT_E_1024mb_0_1:
X        values:
X          part: MT53E512M32D2NP-046WT_E
X          size: '1024'
X          slot: '0'
X          timing: LPDDR4-3733
X      MT53E512M32D2NP-046WT_E_1024mb_1_1:
X        values:
X          part: MT53E512M32D2NP-046WT_E
X          size: '1024'
X          slot: '1'
X          timing: LPDDR4-3733
X      MT53E512M32D2NP-046WT_E_1024mb_2_1:
X        values:
X          part: MT53E512M32D2NP-046WT_E
X          size: '1024'
X          slot: '2'
X          timing: LPDDR4-3733
X      MT53E512M32D2NP-046WT_E_1024mb_3_1:
X        values:
X          part: MT53E512M32D2NP-046WT_E
X          size: '1024'
X          slot: '3'
X          timing: LPDDR4-3733
X      MT53E512M32D2NP-046WT_E_1024mb_4_1:
X        values:
X          part: MT53E512M32D2NP-046WT_E
X          size: '1024'
X          slot: '4'
X          timing: LPDDR4-3733
X      MT53E512M32D2NP-046WT_E_1024mb_5_1:
X        values:
X          part: MT53E512M32D2NP-046WT_E
X          size: '1024'
X          slot: '5'
X          timing: LPDDR4-3733
X      MT53E512M32D2NP-046WT_E_1024mb_6_1:
X        values:
X          part: MT53E512M32D2NP-046WT_E
X          size: '1024'
X          slot: '6'
X          timing: LPDDR4-3733
X      MT53E512M32D2NP-046WT_E_1024mb_7_1:
X        values:
X          part: MT53E512M32D2NP-046WT_E
X          size: '1024'
X          slot: '7'
X          timing: LPDDR4-3733
X      H9HCNNNCPMMLXR-NEE_2048mb_0:
X        values:
X          part: H9HCNNNCPMMLXR-NEE
X          size: '2048'
X          slot: '0'
X          timing: LPDDR4-4267
X      H9HCNNNCPMMLXR-NEE_2048mb_1:
X        values:
X          part: H9HCNNNCPMMLXR-NEE
X          size: '2048'
X          slot: '1'
X          timing: LPDDR4-4267
X      H9HCNNNCPMMLXR-NEE_2048mb_2:
X        values:
X          part: H9HCNNNCPMMLXR-NEE
X          size: '2048'
X          slot: '2'
X          timing: LPDDR4-4267
X      H9HCNNNCPMMLXR-NEE_2048mb_3:
X        values:
X          part: H9HCNNNCPMMLXR-NEE
X          size: '2048'
X          slot: '3'
X          timing: LPDDR4-4267
X      H9HCNNNCPMMLXR-NEE_2048mb_4:
X        values:
X          part: H9HCNNNCPMMLXR-NEE
X          size: '2048'
X          slot: '4'
X          timing: LPDDR4-4267
X      H9HCNNNCPMMLXR-NEE_2048mb_5:
X        values:
X          part: H9HCNNNCPMMLXR-NEE
X          size: '2048'
X          slot: '5'
X          timing: LPDDR4-4267
X      H9HCNNNCPMMLXR-NEE_2048mb_6:
X        values:
X          part: H9HCNNNCPMMLXR-NEE
X          size: '2048'
X          slot: '6'
X          timing: LPDDR4-4267
X      H9HCNNNCPMMLXR-NEE_2048mb_7:
X        values:
X          part: H9HCNNNCPMMLXR-NEE
X          size: '2048'
X          slot: '7'
X          timing: LPDDR4-4267
X      H9HCNNNCPMMLXR-NEE_4096mb_0:
X        status: unqualified
X        values:
X          part: H9HCNNNCPMMLXR-NEE
X          size: '4096'
X          slot: '0'
X          timing: LPDDR4X-1600,LPDDR4X-2400,LPDDR4X-3200
X      H9HCNNNCPMMLXR-NEE_4096mb_1:
X        status: unqualified
X        values:
X          part: H9HCNNNCPMMLXR-NEE
X          size: '4096'
X          slot: '1'
X          timing: LPDDR4X-1600,LPDDR4X-2400,LPDDR4X-3200
X      H9HCNNNCPMMLXR-NEE_4096mb_2:
X        status: unqualified
X        values:
X          part: H9HCNNNCPMMLXR-NEE
X          size: '4096'
X          slot: '2'
X          timing: LPDDR4X-1600,LPDDR4X-2400,LPDDR4X-3200
X      H9HCNNNCPMMLXR-NEE_4096mb_3:
X        status: unqualified
X        values:
X          part: H9HCNNNCPMMLXR-NEE
X          size: '4096'
X          slot: '3'
X          timing: LPDDR4X-1600,LPDDR4X-2400,LPDDR4X-3200
X      H9HCNNNCPMMLXR-NEE_4096mb_4:
X        status: unqualified
X        values:
X          part: H9HCNNNCPMMLXR-NEE
X          size: '4096'
X          slot: '4'
X          timing: LPDDR4X-1600,LPDDR4X-2400,LPDDR4X-3200
X      H9HCNNNCPMMLXR-NEE_4096mb_5:
X        status: unqualified
X        values:
X          part: H9HCNNNCPMMLXR-NEE
X          size: '4096'
X          slot: '5'
X          timing: LPDDR4X-1600,LPDDR4X-2400,LPDDR4X-3200
X      H9HCNNNCPMMLXR-NEE_4096mb_6:
X        status: unqualified
X        values:
X          part: H9HCNNNCPMMLXR-NEE
X          size: '4096'
X          slot: '6'
X          timing: LPDDR4X-1600,LPDDR4X-2400,LPDDR4X-3200
X      H9HCNNNCPMMLXR-NEE_4096mb_7:
X        status: unqualified
X        values:
X          part: H9HCNNNCPMMLXR-NEE
X          size: '4096'
X          slot: '7'
X          timing: LPDDR4X-1600,LPDDR4X-2400,LPDDR4X-3200
X      H9HCNNNBKMMLXR-NEE_1024mb_0_1:
X        values:
X          part: H9HCNNNBKMMLXR-NEE
X          size: '1024'
X          slot: '0'
X          timing: LPDDR4-3733
X      H9HCNNNBKMMLXR-NEE_1024mb_1_1:
X        values:
X          part: H9HCNNNBKMMLXR-NEE
X          size: '1024'
X          slot: '1'
X          timing: LPDDR4-3733
X      H9HCNNNBKMMLXR-NEE_1024mb_2_1:
X        values:
X          part: H9HCNNNBKMMLXR-NEE
X          size: '1024'
X          slot: '2'
X          timing: LPDDR4-3733
X      H9HCNNNBKMMLXR-NEE_1024mb_3_1:
X        values:
X          part: H9HCNNNBKMMLXR-NEE
X          size: '1024'
X          slot: '3'
X          timing: LPDDR4-3733
X      H9HCNNNBKMMLXR-NEE_1024mb_4_1:
X        values:
X          part: H9HCNNNBKMMLXR-NEE
X          size: '1024'
X          slot: '4'
X          timing: LPDDR4-3733
X      H9HCNNNBKMMLXR-NEE_1024mb_5_1:
X        values:
X          part: H9HCNNNBKMMLXR-NEE
X          size: '1024'
X          slot: '5'
X          timing: LPDDR4-3733
X      H9HCNNNBKMMLXR-NEE_1024mb_6_1:
X        values:
X          part: H9HCNNNBKMMLXR-NEE
X          size: '1024'
X          slot: '6'
X          timing: LPDDR4-3733
X      H9HCNNNBKMMLXR-NEE_1024mb_7_1:
X        values:
X          part: H9HCNNNBKMMLXR-NEE
X          size: '1024'
X          slot: '7'
X          timing: LPDDR4-3733
X  ec_flash_chip:
X    items:
X      NPCX796F:
X        status: unqualified
X        values:
X          name: NPCX796F
X          vendor: Nuvoton
X      NPCX797F:
X        values:
X          name: NPCX797F
X          vendor: Nuvoton
X  embedded_controller:
X    items:
X      NPCX796F:
X        status: unqualified
X        values:
X          name: NPCX796F
X          vendor: Nuvoton
X      NPCX797F:
X        values:
X          name: NPCX797F
X          vendor: Nuvoton
X  flash_chip:
X    items:
X      W25Q256JV_M:
X        values:
X          name: W25Q256JV_M
X          vendor: Winbond
X  storage:
X    items:
X      storage_a9c1468f:
X        status: unqualified
X        values:
X          class: '0x010802'
X          device: '0x5003'
X          sectors: '500118192'
X          vendor: '0x15b7'
X      storage_hynix_256gb:
X        status: unqualified
X        values:
X          class: '0x010802'
X          device: '0x1327'
X          sectors: '500118192'
X          vendor: '0x1c5c'
X      storage_wd_256gb:
X        values:
X          class: '0x010802'
X          device: '0x5009'
X          sectors: '500118192'
X          vendor: '0x15b7'
X      storage_hynix_128gb:
X        values:
X          class: '0x010802'
X          device: '0x1327'
X          sectors: '250069680'
X          vendor: '0x1c5c'
X  stylus:
X    items:
X      ELAN9008_00_04F3_2C1C:
X        values:
X          name: ELAN9008:00 04F3:2C1C
X          product: 2c1c
X          vendor: 04f3
X  touchscreen:
X    items:
X      ELAN9008_00_04F3_2C1C:
X        values:
X          name: ELAN9008:00 04F3:2C1C
X          product: 2c1c
X          vendor: 04f3
X  touchpad:
X    items:
X      Elan_Touchpad:
X        values:
X          name: Elan Touchpad
X          product: 00c2
X          vendor: 04f3
X  tpm:
X    items:
X      '2_0_0_0':
X        values:
X          manufacturer_info: 43524f53
X          version: 2.0.0.0
X  usb_hosts:
X    items:
X      usb_hosts_bc72c0a2:
X        values:
X          device: '0xa0ed'
X          revision_id: '0x20'
X          vendor: '0x8086'
X      usb_hosts_6f950346:
X        values:
X          device: '0x9a13'
X          revision_id: '0x01'
X          vendor: '0x8086'
X  video:
X    items:
X      Quanta:
X        values:
X          bcdDevice: '0003'
X          bus_type: usb
X          idProduct: 30d2
X          idVendor: 0408
X          manufacturer: Quanta
X          product: USB2.0 HD UVC WebCam
X          type: webcam
X      Quanta_30d6:
X        values:
X          bcdDevice: '0002'
X          bus_type: usb
X          idProduct: 30d6
X          idVendor: 0408
X          manufacturer: Quanta
X          product: USB2.0 HD UVC WebCam
X          type: webcam
X  wireless:
X    items:
X      wireless_cc8d134f:
X        values:
X          device: '0xa0f0'
X          revision_id: '0x20'
X          vendor: '0x8086'
X  firmware_keys:
X    items:
X      firmware_keys_dev:
X        status: unqualified
X        values:
X          key_recovery: kv3#c14bd720b70d97394257e3e826bd8f43de48d4ed#devkeys/recovery
X          key_root: kv3#b11d74edd286c144e1135b49e7f0bc20cf041f10#devkeys/rootkey
X      firmware_keys_dev_evt:
X        status: unqualified
X        values:
X          key_recovery: kv3#990cae4b1ac8b89ca3c6b7e1b9b9fc10a5c455d7
X          key_root: kv3#b083b092865983c6b19990c783f0d46ec708d3d6
X      firmware_keys_mp:
X        values:
X          key_recovery: kv3#f2141ccb50eec334004f818ceb2821c9c0fb292d
X          key_root: kv3#1331a6ffad2d278a17d0236ebc5cc4874f48521a
X  ro_main_firmware:
X    items:
X      Google_Delbin_13360_0_2020_07_20_1857:
X        status: unqualified
X        values:
X          hash: cadffc7cf4d3ff8664b1b77423427e44f1ab28e908166bc99809a4b1f8edae05
X          version: Google_Delbin.13360.0.2020_07_20_1857
X      Google_Delbin_13406_0_0:
X        status: unqualified
X        values:
X          hash: e272a80334dfb96c483c040cc8416ceda7a7ac81dc1830c6fafa3ce9e49bb025
X          version: Google_Delbin.13406.0.0
X      Google_Delbin_13432_0_2020_08_31_2251:
X        status: unqualified
X        values:
X          hash: abbc614e3eaf4364a28928b77c95ed7ca209d69c61c9094d50ecb58187775bfd
X          version: Google_Delbin.13432.0.2020_08_31_2251
X      Google_Delbin_13521_58_0:
X        status: unqualified
X        values:
X          hash: ccfc0cd4706b321c8cbf83e9d0d73e9d5c14ff438e0adde6d044be246f654de8
X          version: Google_Delbin.13521.58.0
X      Google_Delbin_13521_62_0:
X        status: unqualified
X        values:
X          hash: 75f371f477fee4b00a47c02c4b625a9a13256fca69fc45e660c5dd6d16ed031f
X          version: Google_Delbin.13521.62.0
X      Google_Delbin_13672_30_0:
X        status: unqualified
X        values:
X          hash: d649267762a47eacfee242da4579e667725cc7f292ad4b762e7032e699382039
X          version: Google_Delbin.13672.30.0
X      Google_Delbin_13672_39_0:
X        values:
X          hash: 32796087db53971e1e2cf5845a26172cc1dcad3901375e8a258db3f2a3c870e9
X          version: Google_Delbin.13672.39.0
X  ro_ec_firmware:
X    items:
X      delbin_v2_0_4451_b5e4045dc:
X        status: unqualified
X        values:
X          hash: db361e5e20dd3e2a216100b196c8bfd7a0b6b37ca19a9089f0d4a37a512bfbf3
X          version: delbin_v2.0.4451-b5e4045dc
X      delbin_v2_0_5090_20b44a3f5:
X        status: unqualified
X        values:
X          hash: 5d8c681a2cb8b0474f81dfb52fdfe5cd34b267ab516de002ab745f3ae471ee06
X          version: delbin_v2.0.5090-20b44a3f5
X      delbin_v2_0_5214cf7b8c404:
X        status: unqualified
X        values:
X          hash: 1148249ecaabe61965cdac4949a4b5d91f3d97200903184a57edc92320a59dee
X          version: delbin_v2.0.5214+cf7b8c404
X      delbin_v2_0_6343_aef401423:
X        status: unqualified
X        values:
X          hash: 5edd2d83b574a7d000442fde0aa758a6642333f0c134e09ca286ac1b20312127
X          version: delbin_v2.0.6343-aef401423
X      delbin_v2_0_6343_aef401423_1:
X        status: unqualified
X        values:
X          hash: 015e3a81ce8e9963070b64e34a2377dc0d7d391114b06c6e02ac9d49a10db4a0
X          version: delbin_v2.0.6343-aef401423
X      delbin_v2_0_6785_1333a05a3:
X        status: unqualified
X        values:
X          hash: 407308c6b065480766be2d6f729c603a2ac17c480f66d640b5ad645eddf98739
X          version: delbin_v2.0.6785-1333a05a3
X      delbin_v2_0_7093_edfd0fddb:
X        values:
X          hash: 3e9e6549958c78c42d9372cb577ca8bdcb9e06d1b992f20c2b772f5935f8341c
X          version: delbin_v2.0.7093-edfd0fddb
X
Xrules:
X- name: device_info.image_id
X  evaluate: SetImageId('PVT')
SHAR_EOF
  (set 20 21 03 29 22 12 49 'DELBIN'
   eval "${shar_touch}") && \
  chmod 0644 'DELBIN'
if test $? -ne 0
then ${echo} "restore of DELBIN failed"
fi
  if ${md5check}
  then (
       ${MD5SUM} -c >/dev/null 2>&1 || ${echo} 'DELBIN': 'MD5 check failed'
       ) << \SHAR_EOF
febd25865f78955723c5539d100e853f  DELBIN
SHAR_EOF

else
test `LC_ALL=C wc -c < 'DELBIN'` -ne 25164 && \
  ${echo} "restoration warning:  size of 'DELBIN' is not 25164"
  fi
fi
if rm -fr ${lock_dir}
then ${echo} "x - removed lock directory ${lock_dir}."
else ${echo} "x - failed to remove lock directory ${lock_dir}."
     exit 1
fi
exit 0